language: ruby
rvm:
 - 2.3.3
sudo: required

before_install:
  - bundle config git.allow_insecure true
  - gem install bundler
  - gem install activeadmin -v '1.0.0.pre2'

install:
  - bundle install

script:
  - bundle exec rake db:test:prepare
  - bundle exec rake spec:travis
